# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4eccbe70658c13a21ee5424b4e16510f6f00f843477516edc2d9563e56960f217a6bd24db7aabdfd52f211a68c6d52ddb350c7ba66ae49c09b181c20c33527b

test:
  secret_key_base: 773fd8d9b5b4da9927b2b2222c8a3c803ce93ca79cb23158693cdea53091cb92fd03fe2631762ca6b699248e391e2a0a3fe8f5996f32f2e585e8ee23235b8309

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
